apiVersion: v1
kind: ConfigMap
metadata:
  name: api
  namespace: --environment--
  labels:
    app: api
data:
  Jwt__Issuer: Golden
  Jwt__Audience: Golden
  LogInfo: 'true'
  ASPNETCORE_URLS: https://+;http://+
  ASPNETCORE_HTTPS_PORT: '443'
  ASPNETCORE_Kestrel__Certificates__Default__Path: /https/cert.pfx
  Notification__To: soporte.sistemas@inglesefe.com
  UrlWeb: --urlChangePassword--

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: --environment--
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      volumes:
        - name: cert-volume
          secret:
            secretName: certificates
      containers:
        - name: api
          image: ghcr.io/inglesefe/api:--version--
          volumeMounts:
            - name: cert-volume
              readOnly: true
              mountPath: "/https"
          ports:
            - containerPort: 80
            - containerPort: 443
          envFrom:
            - configMapRef:
                name: api
            - secretRef:
                name: api

---

apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: --environment--
  labels:
    app: api
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      protocol: TCP
      nodePort: --portHttp--
    - port: 443
      name: https
      protocol: TCP
      nodePort: --portHttps--
  selector:
    app: api